
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 24 22:07:11 CET 2018
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULT = 3;
  public static final int CONST = 19;
  public static final int INTEGER = 42;
  public static final int INT = 11;
  public static final int WRITEINT = 36;
  public static final int ARRAY = 16;
  public static final int FOR = 24;
  public static final int MINUS = 2;
  public static final int NOT = 26;
  public static final int TYPE = 33;
  public static final int OR = 15;
  public static final int DIV = 40;
  public static final int BEGIN = 17;
  public static final int WRITELN = 37;
  public static final int IF = 25;
  public static final int CLCOR = 8;
  public static final int OF = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int ASIG = 12;
  public static final int RETURN = 29;
  public static final int EQUAL = 14;
  public static final int TRUE = 32;
  public static final int CLPAR = 10;
  public static final int error = 1;
  public static final int COMA = 41;
  public static final int PCOMA = 5;
  public static final int MODULE = 4;
  public static final int PUNTOS = 6;
  public static final int ELSE = 21;
  public static final int WRITESTRING = 35;
  public static final int IDEN = 38;
  public static final int TO = 31;
  public static final int THEN = 30;
  public static final int OPCOR = 7;
  public static final int END = 22;
  public static final int STRING = 39;
  public static final int OPPAR = 9;
  public static final int FALSE = 23;
  public static final int VAR = 34;
  public static final int PROCEDURE = 28;
  public static final int MORE = 13;
  public static final int DO = 20;
}

